In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [3]:
a.ndim

1

In [4]:
#get shape
a.shape

(4,)

In [5]:
b=np.array([[1,2,3],[4,5,6]])

In [6]:
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#get dimension
b.ndim

2

In [10]:
#get type
b.dtype


dtype('int32')

In [11]:
#get size
b.itemsize


4

In [12]:
#get totalsize
b.nbytes


24

In [13]:
#accessing chanfing spacific elements, rows, cols

In [48]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a.shape)

(2, 7)


In [17]:
#get specific row, col -- [r,c]
#a[1,3] ----1
#a[0,3] -----4
#we can also give negative numbers
a[0,-2]

6

In [18]:
#[startindex:endindex:stepindex]
#printing numbers between 2 nd 6
a[0,1:5]

array([2, 3, 4, 5])

In [19]:
#entire row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#entire column
a[:,4]

array([ 5, 12])

In [21]:
a[0,1:-1:2]

array([2, 4, 6])

In [25]:
#changing element
a[1,5]=80
print(a)

a[:,2]=60
print(a)

[[ 1  2 60  4 60  6  7]
 [ 8  9 60 11 60 80 14]]
[[ 1  2 60  4 60  6  7]
 [ 8  9 60 11 60 80 14]]


In [29]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.shape
            

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [35]:
#get specific element
b[0,1,1]
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [38]:
#replace
b[:,1,:] = [[8,9],[5,4]]
print(b)

[[[1 2]
  [8 9]]

 [[5 6]
  [5 4]]]


# Initializing different types of arrays

In [42]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.ones((2,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [45]:
np.full((2,2),80,dtype='int32')

array([[80, 80],
       [80, 80]])

In [51]:
#any other number (full_line)
np.full_like(a.shape,4)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [52]:
#random decimal numbers
np.random.rand(4,2)

array([[0.80071732, 0.18585449],
       [0.64096973, 0.12564113],
       [0.48610382, 0.76599755],
       [0.07255002, 0.98735529]])

In [54]:
#if you want pass shape to random decimal numbers
np.random.random_sample(a.shape)

array([[0.74485287, 0.22066147, 0.98000101, 0.61121852, 0.03143613,
        0.93742997, 0.56564501],
       [0.63197665, 0.81021402, 0.4214926 , 0.37762673, 0.97680737,
        0.24014088, 0.67945839]])

In [60]:
#ranom integer values,arg1-->number range arg2--> size of matrix
np.random.randint(7,size=(3,3))
np.random.randint(-4,8,size=(3,3))

array([[6, 2, 5],
       [3, 1, 6],
       [7, 5, 6]])

In [61]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
#repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#we need below matrix
# [[1. 1. 1. 1. 1.]
# [1. 0. 0. 0. 1.]
# [1. 0. 9. 0. 1.]
# [1. 0. 0. 0. 1.]
# [1. 1. 1. 1. 1.]]
c = np.ones((5,5))
print(c)
z=np.zeros((3,3))
z[1,1]=9
print(z)
c[1:4,1:4]=z
print(c)

# be careful when copying arrays"

In [80]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Linear Algebra

In [86]:
a = np.full((3,2),2)
print(a)

b=np.ones((2,3))
print(b)
np.matmul(a,b)

[[2 2]
 [2 2]
 [2 2]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [88]:
#determinent
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [89]:
#finding eigen values
np.linalg.eig(c)

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

# statistics

In [92]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [96]:
#axis=0 -->row  axis=1-->column
np.min(stats,axis=1) #it checks min in cols 
np.min(stats)

1

In [95]:
np.max(stats,axis=0)

array([4, 5, 6])

In [98]:
np.sum(stats,axis=1)

array([ 6, 15])

# Reorganizing Arrays

In [100]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [102]:
#reshape -- reshape the array with given row and column
after=before.reshape(4,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [103]:
after = before.reshape(2,2,2)
print(after)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [104]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [105]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
#horizontal stack
h1=np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Load data from file

# Boolean Masking and advanced indexing